### ISSUE TITLE
VGG loss alone

### ISSUE THREAD

**Issue by muxgt** [pbaylies/stylegan-encoder#32]
Hi! I have a small question. How to do original VGG-loss-only with your code? I put VGG loss to 1 and all the others to 0 but still some difference with Puzer for example. Below is the results:

## &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Original&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Puzer&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Pbaylies
![Original_1024256](https://user-images.githubusercontent.com/54779582/67728036-c2fdd280-f9fc-11e9-858e-61c61ab57eae.jpg)![Puzer Adam 500it256](https://user-images.githubusercontent.com/54779582/67728040-c5602c80-f9fc-11e9-9705-9ef4621edfd4.jpg)![Pbaylies VGG 100256](https://user-images.githubusercontent.com/54779582/67728051-c98c4a00-f9fc-11e9-8741-b372552c2a9b.jpg)

The scarf in some reason is not visualized. I don't use face mask. Can you please advice?

**Comment by AzzerAce** [comment]
Hey, it's probably because @pbaylies changed the original vgg loss from L2 in Puzer's repo ([this line](https://github.com/Puzer/stylegan-encoder/blob/1e7e47f9bbb0ca391cdc250af5ad2468250a803c/encoder/perceptual_model.py#L46)) to L1 in 
https://github.com/pbaylies/stylegan-encoder/blob/18919c2565e3947eafc152e320ba573b3e61ad08/encoder/perceptual_model.py#L22-L23
https://github.com/pbaylies/stylegan-encoder/blob/18919c2565e3947eafc152e320ba573b3e61ad08/encoder/perceptual_model.py#L132

You can try replacing the lines and see if that helps.

**Comment by muxgt** [comment]
@AzzerAce Thanks man! It seems to work although some small difference left.
![Pbaylies VGG L2 even200](https://user-images.githubusercontent.com/54779582/67786320-bd959c00-fa7f-11e9-81bb-f460107f4290.jpg)

**Comment by shyanguan** [comment]
> @AzzerAce Thanks man! It seems to work although some small differences left.
> ![Pbaylies VGG L2 even200](https://user-images.githubusercontent.com/54779582/67786320-bd959c00-fa7f-11e9-81bb-f460107f4290.jpg)

Did you change the perceptual loss using L1 loss on the VGG feature? 

I think the main difference is that this repo uses mask but Puzer's repo uses the whole image.
