### ISSUE TITLE
Encode only coarse dlatents

### ISSUE THREAD

**Issue by jakeelwes** [pbaylies/stylegan-encoder#8]
Hey @pbaylies thanks for this repo! :) 
You suggested to predict pose I could train a resnet to predict just the coarse dlatents (Puzer/stylegan-encoder#15).

Would it be something to do with this reshape?
https://github.com/pbaylies/stylegan-encoder/blob/b5ddcd7a820146e3b45182789518e2ff499704f3/train_resnet.py#L162

Or changing the size of W?
https://github.com/pbaylies/stylegan-encoder/blob/b5ddcd7a820146e3b45182789518e2ff499704f3/train_resnet.py#L55-L60

Thanks for your help, sorry I'm not from a ML background.

**Comment by pbaylies** [comment]
Hi @jakeelwes -- for a simpler example, take a look [at this file](https://github.com/pbaylies/stylegan-encoder/files/3286387/train_eff512.py.zip) from issue #1 -- it only predicts a single 512-wide vector for everything, so that includes the pose. This is also what StyleGAN does while training.

I'm not originally from an ML background either, I've just been programming for a long time!
